---
- name: Install etcd dependencies
  yum:
    name: {{item}}
    state: latest
    with_items:
      - git

- name: Download Go
  get_url:
    url: 'https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz'
    dest: '/tmp/go1.8.3.linux-amd64.tar.gz'

- name: Install Go
  command: 'tar -C /usr/local/ -xzf go1.8.3.linux-amd64.tar.gz'

- name: Add go to path
  command: 'export PATH=$PATH:/usr/local/go/bin'

- name: Make sure opt exists
  file:
    path: /opt
    state: directory
    mode: 0755

- name: Clone etcd
  git:
    repo: 'https://github.com/coreos/etcd'
    dest: '/opt/etcd'

- name: build etcd
  command: './build'
  args: 
    chdir: '/opt/etcd'

- name: Add etcd to path
  command: 'export PATH=$PATH:/opt/etcd/bin'

- name: Create etcd config directory
  file: path={{ etcd_conf_dir }} state=directory

- name: Create etcd cert directory
  file: path={{ kube_config_dir }} state=directory
  when: etcd_peer_url_scheme == 'https'

- name: Write etcd config file
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  register: etc_config

- name: copy etcd certificate from ansible host 
  when: etcd_peer_url_scheme == 'https'
  copy: src={{ master_cert_dir }} dest={{ kube_config_dir }}
  register: etcd_cert

- name: Enable and start etcd
  when: etc_config|succeeded
  service: name=etcd enabled=no state=started

- name: Retart etcd
  service: name=etcd state=restarted
  when: etc_config|changed and etcd_cert|changed
  register: etcd_started
