---
# This playbook deploys a kubernetes cluster with the default addons.

# install ssl cert
- hosts: sslhost
  become: true
  roles:
     -  sslcert
  tags:
     -  sslcert

# Install etcd
- hosts: etcd
  become: true
  roles:
   -   etcd
  tags:
    - etcd

# Install flannel
- hosts: all
  become: true
  roles:
   - flannel

# Install docker
- hosts: all
  become: true
  roles:
    - docker
  tags:
    - docker

# install haproxy
- hosts: masters
  become: true
  roles:
    - haproxy
  tags:
    - haproxy

# install kubernetes master services
- hosts: masters
  become: true
  roles:
    - master
  tags:
    - master

# install kubernetes on the nodes
- hosts: node
  become: true
  roles:
    - node
  tags:
    - node
